### ISSUE TITLE
Hatch Bus startup crash (In gtpp built from this repo as of 10.08.21, 11:10 gmt)

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GTPP#23]
I may be wrong, but could be connected with recent Hatch Bus modifications:

`[14:36:05] [Client thread/ERROR] [FML]: Caught exception from miscutils
java.lang.NoSuchMethodError: gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch_InputBus.<init>(ILjava/lang/String;Ljava/lang/String;II)V
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.GT_MetaTileEntity_SuperBus_Input.<init>(GT_MetaTileEntity_SuperBus_Input.java:21) ~[GT_MetaTileEntity_SuperBus_Input.class:?]
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechCustomHatches.makeInputBus(GregtechCustomHatches.java:196) ~[GregtechCustomHatches.class:?]
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechCustomHatches.run3(GregtechCustomHatches.java:129) ~[GregtechCustomHatches.class:?]
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechCustomHatches.run(GregtechCustomHatches.java:23) ~[GregtechCustomHatches.class:?]
	at gtPlusPlus.core.handler.COMPAT_HANDLER.registerGregtechMachines(COMPAT_HANDLER.java:149) ~[COMPAT_HANDLER.class:?]
	at gtPlusPlus.xmod.gregtech.HANDLER_GT.init(HANDLER_GT.java:96) ~[HANDLER_GT.class:?]
	at gtPlusPlus.core.handler.COMPAT_IntermodStaging.init(COMPAT_IntermodStaging.java:47) ~[COMPAT_IntermodStaging.class:?]
	at gtPlusPlus.core.common.CommonProxy.init(CommonProxy.java:164) ~[CommonProxy.class:?]
	at gtPlusPlus.core.proxy.ClientProxy.init(ClientProxy.java:103) ~[ClientProxy.class:?]
	at gtPlusPlus.GTplusplus.init(GTplusplus.java:187) ~[GTplusplus.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]`

Minecraft crashes during the transition from initialization to postinitialization.

[Full crash](https://paste.ee/p/jvlNE)

**Comment by vovaksenov** [comment]
Yes. Makes sense, last GT not installed
